# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: freija.net
email: freija@freija.net
description: > # this means to ignore newlines until "baseurl:"

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://freija.net" # the base hostname & protocol for your site
github_username:  freija

# Build settings
markdown: kramdown
highlighter: rouge

# Add the collections
collections:
- projects
